var windFarmsAll = [
    {
        "type": "FeatureCollection",
        "name": "windFarmsAll_V1",
        "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
        "features": [
            { "type": "Feature", "properties": { "Name": "Muaitheabhal", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.5403, 58.0205] } },
            { "type": "Feature", "properties": { "Name": "Pentland Road (incorporating Beinn Mholach", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.5108, 58.2589] } },
            { "type": "Feature", "properties": { "Name": "Berry Burn", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.62, 57.6097] } },
            { "type": "Feature", "properties": { "Name": "Windy Standard Extension", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.3986, 55.2919] } },
            { "type": "Feature", "properties": { "Name": "Ark Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.0497, 56.5717] } },
            { "type": "Feature", "properties": { "Name": "West Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.1239, 58.8267] } },
            { "type": "Feature", "properties": { "Name": "Harestanes/Forest of Ae", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.5736, 55.2211] } },
            { "type": "Feature", "properties": { "Name": "Carraig Gheal (Loch Awe)", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-5.2372, 56.4333] } },
            { "type": "Feature", "properties": { "Name": "Camster", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.295, 58.4036] } },
            { "type": "Feature", "properties": { "Name": "St Johns Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2411, 56.8653] } },
            { "type": "Feature", "properties": { "Name": "Tormywheel", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.262, 55.8978] } },
            { "type": "Feature", "properties": { "Name": "Dunmaglass", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.3103, 57.3294] } },
            { "type": "Feature", "properties": { "Name": "Over Enoch &amp; Ardoch", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.2547, 55.7272] } },
            { "type": "Feature", "properties": { "Name": "Blackcraig", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.1092, 55.0917] } },
            { "type": "Feature", "properties": { "Name": "Kildrummy", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.9683, 57.2733] } },
            { "type": "Feature", "properties": { "Name": "Drumlithie Feed Mill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.3811, 56.9358] } },
            { "type": "Feature", "properties": { "Name": "Causeymire Extension", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.5086, 58.4294] } },
            { "type": "Feature", "properties": { "Name": "Lochluichart", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.81, 57.6689] } },
            { "type": "Feature", "properties": { "Name": "Hill of Stroupster", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.1453, 58.5814] } },
            { "type": "Feature", "properties": { "Name": "Dungavel Hill wind farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.0769, 55.6011] } },
            { "type": "Feature", "properties": { "Name": "Nutberry Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.9922, 55.5789] } },
            { "type": "Feature", "properties": { "Name": "Black Law 1 (Construction Phase 3)", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.7389, 55.7669] } },
            { "type": "Feature", "properties": { "Name": "Rosehall Woods", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.5494, 58.0039] } },
            { "type": "Feature", "properties": { "Name": "North Yell", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-1.0033, 60.6697] } },
            { "type": "Feature", "properties": { "Name": "Langhope Rig", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.9411, 55.4728] } },
            { "type": "Feature", "properties": { "Name": "Whiteside Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.0228, 55.3236] } },
            { "type": "Feature", "properties": { "Name": "Meikle Carewe resubmission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2867, 57.0205] } },
            { "type": "Feature", "properties": { "Name": "ASDA depot", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.7644, 56.0183] } },
            { "type": "Feature", "properties": { "Name": "Black Law Extension", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.7389, 55.7669] } },
            { "type": "Feature", "properties": { "Name": "Clochnahill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.3039, 56.9386] } },
            { "type": "Feature", "properties": { "Name": "Earlsburn extension", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.0833, 56.0833] } },
            { "type": "Feature", "properties": { "Name": "Mid Hill 1", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.4606, 56.9644] } },
            { "type": "Feature", "properties": { "Name": "Corriegarth Estate", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.8958, 57.3136] } },
            { "type": "Feature", "properties": { "Name": "Muaitheabhal - Secondary Application", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.5403, 58.0205] } },
            { "type": "Feature", "properties": { "Name": "Calliachar resubmission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.8339, 56.5664] } },
            { "type": "Feature", "properties": { "Name": "Aâ??Chruach", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-5.34, 56.1397] } },
            { "type": "Feature", "properties": { "Name": "Barlockhart Wind Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.7694, 54.8742] } },
            { "type": "Feature", "properties": { "Name": "Gordonstown Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.4783, 57.4442] } },
            { "type": "Feature", "properties": { "Name": "Burn of Whilk", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.2225, 58.3578] } },
            { "type": "Feature", "properties": { "Name": "Middleton", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.4086, 55.7458] } },
            { "type": "Feature", "properties": { "Name": "Baile an Truseil Wind Energy Project", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.4958, 58.3808] } },
            { "type": "Feature", "properties": { "Name": "Mains of Bogfechel", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2456, 57.31] } },
            { "type": "Feature", "properties": { "Name": "North Tolsta", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.7095, 58.313] } },
            { "type": "Feature", "properties": { "Name": "Clashindarroch re-submission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.9328, 57.375] } },
            { "type": "Feature", "properties": { "Name": "Crowness Business Park (Site 3)", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.985, 58.9978] } },
            { "type": "Feature", "properties": { "Name": "Rothes Extension - Resubmission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.3797, 57.5369] } },
            { "type": "Feature", "properties": { "Name": "Neilston", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.4689, 55.7503] } },
            { "type": "Feature", "properties": { "Name": "West Knock Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.03, 57.5005] } },
            { "type": "Feature", "properties": { "Name": "Horshader", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.7003, 58.3233] } },
            { "type": "Feature", "properties": { "Name": "Bogenlea", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2917, 57.5603] } },
            { "type": "Feature", "properties": { "Name": "Allt Dearg", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-5.4477, 55.9619] } },
            { "type": "Feature", "properties": { "Name": "Burgar Hill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.1214, 59.1197] } },
            { "type": "Feature", "properties": { "Name": "Upper Stove", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.7317, 58.9544] } },
            { "type": "Feature", "properties": { "Name": "Pogbie Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.8414, 55.8394] } },
            { "type": "Feature", "properties": { "Name": "Hillhead of Auquhirie re-submission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2875, 56.9417] } },
            { "type": "Feature", "properties": { "Name": "Rothiesholm Head", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.6839, 59.085] } },
            { "type": "Feature", "properties": { "Name": "Kingarly", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.0211, 59.1519] } },
            { "type": "Feature", "properties": { "Name": "Ore Bray", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.3261, 58.8267] } },
            { "type": "Feature", "properties": { "Name": "Howe", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.8456, 59.0553] } },
            { "type": "Feature", "properties": { "Name": "Sandybanks", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.7717, 59.1867] } },
            { "type": "Feature", "properties": { "Name": "Spurness", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.5683, 59.2714] } },
            { "type": "Feature", "properties": { "Name": "Gallowhill", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.9886, 59.2975] } },
            { "type": "Feature", "properties": { "Name": "Muirhall", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.5925, 55.7736] } },
            { "type": "Feature", "properties": { "Name": "AG Barr Factory", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.0583, 55.9283] } },
            { "type": "Feature", "properties": { "Name": "Auchtygills Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.0417, 57.5797] } },
            { "type": "Feature", "properties": { "Name": "Clayfords Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.0669, 57.5894] } },
            { "type": "Feature", "properties": { "Name": "Wathegar", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.2408, 58.4414] } },
            { "type": "Feature", "properties": { "Name": "Ewe Hill (first 6 turbines)", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.1242, 55.1767] } },
            { "type": "Feature", "properties": { "Name": "Steps of Grace Community Owned Wind Turbine", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.0239, 55.7928] } },
            { "type": "Feature", "properties": { "Name": "St Fergus Moss", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-1.9197, 57.5728] } },
            { "type": "Feature", "properties": { "Name": "Corrimony", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.6725, 57.333] } },
            { "type": "Feature", "properties": { "Name": "Dundee Cold Stores Ltd", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.0453, 56.4778] } },
            { "type": "Feature", "properties": { "Name": "Greenhill Croft", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.2575, 57.5708] } },
            { "type": "Feature", "properties": { "Name": "Castle of Auchry", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.3725, 57.5503] } },
            { "type": "Feature", "properties": { "Name": "Baile an Truseil Wind Energy Project Phase 1", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.4958, 58.3808] } },
            { "type": "Feature", "properties": { "Name": "Baile an Truseil Wind Energy Project Phase 2", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-6.4958, 58.3808] } },
            { "type": "Feature", "properties": { "Name": "Corriemoillie - resubmission", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-4.7786, 57.6644] } },
            { "type": "Feature", "properties": { "Name": "Newbigging Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.5011, 57.2947] } },
            { "type": "Feature", "properties": { "Name": "Noble Foods", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-3.1794, 56.1653] } },
            { "type": "Feature", "properties": { "Name": "Land to South West of Smiddyhill Farm", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.427, 56.8197] } },
            { "type": "Feature", "properties": { "Name": "Middleton of Rora", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-1.8914, 57.5355] } },
            { "type": "Feature", "properties": { "Name": "Hillhead of Tullo", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-2.3542, 57.3769] } },
            { "type": "Feature", "properties": { "Name": "Land at Overside and Greenwellheads Farms", "Type": "consented", "MW": null, "color": "blue" }, "geometry": { "type": "Point", "coordinates": [-1.9006, 57.5853] } },
            { "type": "Feature", "properties": { "Name": "Clyde Wind Farm", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.6544, 55.4672] } },
            { "type": "Feature", "properties": { "Name": "Baillie Wind farm - Bardnaheigh Farm", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.1278, 58.0478] } },
            { "type": "Feature", "properties": { "Name": "Griffin Forrest", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.7828, 56.5525] } },
            { "type": "Feature", "properties": { "Name": "Torrs Hill", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.3017, 55.1717] } },
            { "type": "Feature", "properties": { "Name": "Novar Extension", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.4342, 57.7144] } },
            { "type": "Feature", "properties": { "Name": "Hill of Towie (formerly Drummuir)", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.0275, 57.4867] } },
            { "type": "Feature", "properties": { "Name": "Gordonbush", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.9364, 58.1092] } },
            { "type": "Feature", "properties": { "Name": "Whitelee Phase I extension", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.2286, 55.6872] } },
            { "type": "Feature", "properties": { "Name": "Little Raith", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.3039, 56.1094] } },
            { "type": "Feature", "properties": { "Name": "Drone Hill", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-2.262, 55.8978] } },
            { "type": "Feature", "properties": { "Name": "Fallago Rig", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-2.6639, 55.8269] } },
            { "type": "Feature", "properties": { "Name": "Kelburn", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.7986, 55.7608] } },
            { "type": "Feature", "properties": { "Name": "Beinn an Tuirc Extension", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-5.57, 55.5656] } },
            { "type": "Feature", "properties": { "Name": "Methlick Farmers Wind Energy Project", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-2.2978, 57.3917] } },
            { "type": "Feature", "properties": { "Name": "Mains of Hatton", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-2.5089, 57.4697] } },
            { "type": "Feature", "properties": { "Name": "Herscha Hill", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-2.4456, 56.9117] } },
            { "type": "Feature", "properties": { "Name": "Whitelee Phase II extension", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.2286, 55.6872] } },
            { "type": "Feature", "properties": { "Name": "Millour Hill", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-4.7769, 55.7367] } },
            { "type": "Feature", "properties": { "Name": "Glenkerie Wind Farm", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.4581, 55.5392] } },
            { "type": "Feature", "properties": { "Name": "FMC Technologies", "Type": "construction", "MW": null, "color": "grey" }, "geometry": { "type": "Point", "coordinates": [-3.445, 56.0522] } },
            { "type": "Feature", "properties": { "Name": "Ardrossan", "Type": "operational", "MW": 24.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8072, 55.6858] } },
            { "type": "Feature", "properties": { "Name": "Braes O Doune", "Type": "operational", "MW": 72.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0625, 56.2761] } },
            { "type": "Feature", "properties": { "Name": "Minsca Farm", "Type": "operational", "MW": 36.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.2164, 55.1128] } },
            { "type": "Feature", "properties": { "Name": "Ardkinglass/Clachan Flats", "Type": "operational", "MW": 15.03, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.9486, 56.2878] } },
            { "type": "Feature", "properties": { "Name": "Edinbane", "Type": "operational", "MW": 41.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-6.4217, 57.4291] } },
            { "type": "Feature", "properties": { "Name": "Boulfruich", "Type": "operational", "MW": 13.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.4333, 58.3] } },
            { "type": "Feature", "properties": { "Name": "Wardlaw Wood (Dalry Community Windfarm)", "Type": "operational", "MW": 18.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.7233, 55.7106] } },
            { "type": "Feature", "properties": { "Name": "Craig Wind Farm", "Type": "operational", "MW": 10.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1094, 55.2128] } },
            { "type": "Feature", "properties": { "Name": "Deucheran Hill", "Type": "operational", "MW": 15.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.5597, 55.6289] } },
            { "type": "Feature", "properties": { "Name": "Bowbeat", "Type": "operational", "MW": 31.2, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1397, 55.7156] } },
            { "type": "Feature", "properties": { "Name": "An Suidhe", "Type": "operational", "MW": 19.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.2191, 56.218] } },
            { "type": "Feature", "properties": { "Name": "Hagshaw Hill", "Type": "operational", "MW": 15.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.9183, 55.5506] } },
            { "type": "Feature", "properties": { "Name": "East Kilbride", "Type": "operational", "MW": 0.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.16, 55.7422] } },
            { "type": "Feature", "properties": { "Name": "Arnish Moor", "Type": "operational", "MW": 3.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-6.4275, 58.1783] } },
            { "type": "Feature", "properties": { "Name": "Bu Farm", "Type": "operational", "MW": 2.7, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.6647, 59.083] } },
            { "type": "Feature", "properties": { "Name": "Forss", "Type": "operational", "MW": 2.32, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.6675, 58.6078] } },
            { "type": "Feature", "properties": { "Name": "Gigha Community", "Type": "operational", "MW": 0.675, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.7544, 55.6681] } },
            { "type": "Feature", "properties": { "Name": "Toddleburn", "Type": "operational", "MW": 27.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8067, 55.7722] } },
            { "type": "Feature", "properties": { "Name": "Michelin Tyre Factory", "Type": "operational", "MW": 4.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8922, 56.483] } },
            { "type": "Feature", "properties": { "Name": "Rothes (Cairn Uish)", "Type": "operational", "MW": 50.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.3714, 57.5372] } },
            { "type": "Feature", "properties": { "Name": "Crystal Rig", "Type": "operational", "MW": 50.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5131, 55.895] } },
            { "type": "Feature", "properties": { "Name": "Pauls Hill", "Type": "operational", "MW": 64.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.4761, 57.4461] } },
            { "type": "Feature", "properties": { "Name": "Crystal Rig 2 (extension)", "Type": "operational", "MW": 117.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5517, 55.9067] } },
            { "type": "Feature", "properties": { "Name": "Myres Hill", "Type": "operational", "MW": 1.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.2783, 55.6917] } },
            { "type": "Feature", "properties": { "Name": "Thorfinn", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1545, 59.1253] } },
            { "type": "Feature", "properties": { "Name": "Beinn Ghlas", "Type": "operational", "MW": 8.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.2722, 56.383] } },
            { "type": "Feature", "properties": { "Name": "Causeymire", "Type": "operational", "MW": 48.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.5086, 58.4294] } },
            { "type": "Feature", "properties": { "Name": "Novar", "Type": "operational", "MW": 17.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.4342, 57.7144] } },
            { "type": "Feature", "properties": { "Name": "Windy Standard", "Type": "operational", "MW": 21.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.205, 55.2919] } },
            { "type": "Feature", "properties": { "Name": "Burgar Hill", "Type": "operational", "MW": 5.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1458, 59.1203] } },
            { "type": "Feature", "properties": { "Name": "Farr Windfarm", "Type": "operational", "MW": 92.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0942, 57.325] } },
            { "type": "Feature", "properties": { "Name": "Northfield wind turbines (Burray)", "Type": "operational", "MW": 0.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8947, 58.8708] } },
            { "type": "Feature", "properties": { "Name": "Boyndie Airfield", "Type": "operational", "MW": 14.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.6047, 57.6464] } },
            { "type": "Feature", "properties": { "Name": "Ben Aketil", "Type": "operational", "MW": 23.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-6.455, 57.4291] } },
            { "type": "Feature", "properties": { "Name": "Kilbraur (Strathbrora)", "Type": "operational", "MW": 47.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.1278, 58.0478] } },
            { "type": "Feature", "properties": { "Name": "Millennium (Glenmoriston)", "Type": "operational", "MW": 40.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8322, 57.1344] } },
            { "type": "Feature", "properties": { "Name": "Black Hill", "Type": "operational", "MW": 28.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.4339, 55.7983] } },
            { "type": "Feature", "properties": { "Name": "Dun Law", "Type": "operational", "MW": 17.16, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8603, 55.8075] } },
            { "type": "Feature", "properties": { "Name": "Glens of Foudland", "Type": "operational", "MW": 26.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.6428, 57.4244] } },
            { "type": "Feature", "properties": { "Name": "Forss Ext", "Type": "operational", "MW": 5.2, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.6697, 58.6078] } },
            { "type": "Feature", "properties": { "Name": "Artfield Fell", "Type": "operational", "MW": 19.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.7664, 54.9661] } },
            { "type": "Feature", "properties": { "Name": "Tangy", "Type": "operational", "MW": 12.75, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.6791, 55.4939] } },
            { "type": "Feature", "properties": { "Name": "Hadyard Hill", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.723, 55.2458] } },
            { "type": "Feature", "properties": { "Name": "Drumderg", "Type": "operational", "MW": 36.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.3564, 56.6794] } },
            { "type": "Feature", "properties": { "Name": "Beinn an Tuirc", "Type": "operational", "MW": 30.36, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.57, 55.5656] } },
            { "type": "Feature", "properties": { "Name": "Beinn Tharsuinn", "Type": "operational", "MW": 30.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.3322, 57.8017] } },
            { "type": "Feature", "properties": { "Name": "Cruach Mhor", "Type": "operational", "MW": 29.75, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.1561, 56.04] } },
            { "type": "Feature", "properties": { "Name": "Hare Hill", "Type": "operational", "MW": 13.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.1178, 55.3517] } },
            { "type": "Feature", "properties": { "Name": "Black Law 1 (Construction Phase 1)", "Type": "operational", "MW": 96.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.7389, 55.7669] } },
            { "type": "Feature", "properties": { "Name": "Green Knowes", "Type": "operational", "MW": 27.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.6669, 56.2489] } },
            { "type": "Feature", "properties": { "Name": "Burradale Phase 1", "Type": "operational", "MW": 1.98, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-1.2361, 60.1647] } },
            { "type": "Feature", "properties": { "Name": "Burradale Phase 2", "Type": "operational", "MW": 1.7, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-1.2361, 60.1647] } },
            { "type": "Feature", "properties": { "Name": "Dummuie", "Type": "operational", "MW": 12.25, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.7314, 57.4092] } },
            { "type": "Feature", "properties": { "Name": "Sigurd", "Type": "operational", "MW": 1.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1492, 59.1314] } },
            { "type": "Feature", "properties": { "Name": "Tullo", "Type": "operational", "MW": 17.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.3997, 56.8353] } },
            { "type": "Feature", "properties": { "Name": "Long Park", "Type": "operational", "MW": 38.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8364, 55.6731] } },
            { "type": "Feature", "properties": { "Name": "Spurness Wind Farm", "Type": "operational", "MW": 8.25, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.6894, 59.1861] } },
            { "type": "Feature", "properties": { "Name": "Dalswinton", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.6736, 55.1703] } },
            { "type": "Feature", "properties": { "Name": "Wether Hill", "Type": "operational", "MW": 18.2, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0417, 55.2222] } },
            { "type": "Feature", "properties": { "Name": "Aikengall", "Type": "operational", "MW": 48.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.4578, 55.9267] } },
            { "type": "Feature", "properties": { "Name": "Lochhead Farm", "Type": "operational", "MW": 6.15, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.9461, 55.7047] } },
            { "type": "Feature", "properties": { "Name": "Lochelbank", "Type": "operational", "MW": 9.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.4303, 56.3067] } },
            { "type": "Feature", "properties": { "Name": "Fintry (The FREE Turbine)", "Type": "operational", "MW": 2.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.2167, 56.05] } },
            { "type": "Feature", "properties": { "Name": "Earlsburn", "Type": "operational", "MW": 37.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0833, 56.0833] } },
            { "type": "Feature", "properties": { "Name": "Findhorn Foundation", "Type": "operational", "MW": 0.75, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.58, 57.6572] } },
            { "type": "Feature", "properties": { "Name": "Fairburn Estate", "Type": "operational", "MW": 40.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.6464, 57.5297] } },
            { "type": "Feature", "properties": { "Name": "Mark Hill", "Type": "operational", "MW": 56.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.9325, 54.9936] } },
            { "type": "Feature", "properties": { "Name": "Achairn Farm", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.192, 58.4372] } },
            { "type": "Feature", "properties": { "Name": "Pates Hill", "Type": "operational", "MW": 14.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.6536, 55.8267] } },
            { "type": "Feature", "properties": { "Name": "Tangy Extension", "Type": "operational", "MW": 5.95, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.6791, 55.4939] } },
            { "type": "Feature", "properties": { "Name": "Arecleoch", "Type": "operational", "MW": 120.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8822, 55.0533] } },
            { "type": "Feature", "properties": { "Name": "Hagshaw Hill Extension", "Type": "operational", "MW": 26.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.9008, 55.5561] } },
            { "type": "Feature", "properties": { "Name": "Dun Law extension", "Type": "operational", "MW": 29.75, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8603, 55.8075] } },
            { "type": "Feature", "properties": { "Name": "Balnamoon Farm", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.8631, 57.5867] } },
            { "type": "Feature", "properties": { "Name": "Watten (Bilbster)", "Type": "operational", "MW": 3.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.3133, 58.4719] } },
            { "type": "Feature", "properties": { "Name": "Black Law 1 (Construction Phase 2)", "Type": "operational", "MW": 27.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.7389, 55.7669] } },
            { "type": "Feature", "properties": { "Name": "Tiree Community Wind Turbine", "Type": "operational", "MW": 0.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-6.7577, 56.5355] } },
            { "type": "Feature", "properties": { "Name": "Achany Estate", "Type": "operational", "MW": 38.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.5317, 58.0044] } },
            { "type": "Feature", "properties": { "Name": "Burnfoot Hill", "Type": "operational", "MW": 26.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.7669, 56.2114] } },
            { "type": "Feature", "properties": { "Name": "Pendine (Parc Cynog Extension I)", "Type": "operational", "MW": 4.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.5778, 55.8578] } },
            { "type": "Feature", "properties": { "Name": "Greendykeside Wind Farm", "Type": "operational", "MW": 4.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.9019, 55.9083] } },
            { "type": "Feature", "properties": { "Name": "Carcant", "Type": "operational", "MW": 6.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.0136, 55.7617] } },
            { "type": "Feature", "properties": { "Name": "Craigengelt Hill", "Type": "operational", "MW": 20.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0505, 56.0553] } },
            { "type": "Feature", "properties": { "Name": "Beatrice", "Type": "operational", "MW": 10.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.0931, 58.1055] } },
            { "type": "Feature", "properties": { "Name": "Ardrossan Extension", "Type": "operational", "MW": 6.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8072, 55.6858] } },
            { "type": "Feature", "properties": { "Name": "North Redbog", "Type": "operational", "MW": 1.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.0058, 57.5858] } },
            { "type": "Feature", "properties": { "Name": "North Rhins", "Type": "operational", "MW": 22.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-5.0869, 54.8675] } },
            { "type": "Feature", "properties": { "Name": "Holodyke", "Type": "operational", "MW": 0.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1881, 59.0758] } },
            { "type": "Feature", "properties": { "Name": "Millennium (Glenmoriston) extension", "Type": "operational", "MW": 10.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8322, 57.1344] } },
            { "type": "Feature", "properties": { "Name": "Strath of Brydock", "Type": "operational", "MW": 4.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5811, 57.6278] } },
            { "type": "Feature", "properties": { "Name": "St Johns Wells", "Type": "operational", "MW": 2.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.3344, 57.4228] } },
            { "type": "Feature", "properties": { "Name": "Beinn Tharsuinn extension (Beinn nan Oighrean)", "Type": "operational", "MW": 4.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.3322, 57.8017] } },
            { "type": "Feature", "properties": { "Name": "Hill of Balquhindachy (Extension)", "Type": "operational", "MW": 1.7, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.2386, 57.473] } },
            { "type": "Feature", "properties": { "Name": "Hill of Balquhindachy", "Type": "operational", "MW": 0.85, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.2386, 57.473] } },
            { "type": "Feature", "properties": { "Name": "Crystal Rig 2a (aka Ila Project)", "Type": "operational", "MW": 20.7, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5439, 55.9042] } },
            { "type": "Feature", "properties": { "Name": "Crystal Rig 1a", "Type": "operational", "MW": 12.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5131, 55.895] } },
            { "type": "Feature", "properties": { "Name": "Hill of Fiddes", "Type": "operational", "MW": 6.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.1144, 57.3155] } },
            { "type": "Feature", "properties": { "Name": "Hill of Eastertown (Mackies)", "Type": "operational", "MW": 2.55, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.3975, 57.3769] } },
            { "type": "Feature", "properties": { "Name": "Millennium Ext 2", "Type": "operational", "MW": 15.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8322, 57.1344] } },
            { "type": "Feature", "properties": { "Name": "Boyndie Extension", "Type": "operational", "MW": 2.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.6047, 57.6464] } },
            { "type": "Feature", "properties": { "Name": "Liniclate Wind Farm", "Type": "operational", "MW": 0.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-7.3611, 57.4216] } },
            { "type": "Feature", "properties": { "Name": "Whitelee", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.2286, 55.6872] } },
            { "type": "Feature", "properties": { "Name": "Ben Aketil extension", "Type": "operational", "MW": 4.6, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-6.4486, 57.4272] } },
            { "type": "Feature", "properties": { "Name": "Hammars Hill", "Type": "operational", "MW": 4.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.0753, 59.0947] } },
            { "type": "Feature", "properties": { "Name": "Methil Docks", "Type": "operational", "MW": 0.75, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.0083, 56.1822] } },
            { "type": "Feature", "properties": { "Name": "Kilbraur extension", "Type": "operational", "MW": 20.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.1278, 58.0478] } },
            { "type": "Feature", "properties": { "Name": "Hill of Burns", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.4294, 57.4047] } },
            { "type": "Feature", "properties": { "Name": "Skelmonae", "Type": "operational", "MW": 3.2, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.185, 57.4467] } },
            { "type": "Feature", "properties": { "Name": "Strath of Brydock ext", "Type": "operational", "MW": 2.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.5811, 57.6278] } },
            { "type": "Feature", "properties": { "Name": "Newstead", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.3128, 57.5425] } },
            { "type": "Feature", "properties": { "Name": "Ednie Farm", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-1.8547, 57.55] } },
            { "type": "Feature", "properties": { "Name": "Cowhill", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.4242, 57.3928] } },
            { "type": "Feature", "properties": { "Name": "Westray Community wind turbine", "Type": "operational", "MW": 0.9, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.9886, 59.2975] } },
            { "type": "Feature", "properties": { "Name": "Burgar Hill", "Type": "operational", "MW": 2.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1528, 59.1203] } },
            { "type": "Feature", "properties": { "Name": "Cairnmore Farm", "Type": "operational", "MW": 2.55, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.825, 57.3083] } },
            { "type": "Feature", "properties": { "Name": "Gairnieston Farm", "Type": "operational", "MW": 2.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.4214, 57.5914] } },
            { "type": "Feature", "properties": { "Name": "Braiden Hill", "Type": "operational", "MW": 0.8, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.0094, 55.8758] } },
            { "type": "Feature", "properties": { "Name": "Burgar Hill", "Type": "operational", "MW": 3.5, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.1403, 59.1094] } },
            { "type": "Feature", "properties": { "Name": "Muirhall - resubmission", "Type": "operational", "MW": 12.3, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-3.5839, 55.7611] } },
            { "type": "Feature", "properties": { "Name": "House O Hill", "Type": "operational", "MW": 2.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.0408, 57.6172] } },
            { "type": "Feature", "properties": { "Name": "Upper Ardgrain", "Type": "operational", "MW": 2.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.0675, 57.4005] } },
            { "type": "Feature", "properties": { "Name": "Cairnhill", "Type": "operational", "MW": 2.4, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-2.3717, 57.5569] } },
            { "type": "Feature", "properties": { "Name": "Girvan Community Hospital", "Type": "operational", "MW": 0.0, "color": "green" }, "geometry": { "type": "Point", "coordinates": [-4.8505, 55.2469] } },
            { "type": "Feature", "properties": { "Name": "Afton", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.1711, 55.3108] } },
            { "type": "Feature", "properties": { "Name": "Meall Mhor", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-5.463, 55.9183] } },
            { "type": "Feature", "properties": { "Name": "Ewe Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.1242, 55.1767] } },
            { "type": "Feature", "properties": { "Name": "Shawbost &amp; Dalmore", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-6.0697, 58.3328] } },
            { "type": "Feature", "properties": { "Name": "Broadmeadows", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.9292, 55.5647] } },
            { "type": "Feature", "properties": { "Name": "Dunbeath", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.5014, 58.2589] } },
            { "type": "Feature", "properties": { "Name": "Bracco", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.8794, 55.8728] } },
            { "type": "Feature", "properties": { "Name": "Bettyhill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.2236, 58.5242] } },
            { "type": "Feature", "properties": { "Name": "Park Estate (Pairc)", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-6.5058, 58.5039] } },
            { "type": "Feature", "properties": { "Name": "Viking Wind Project", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-1.2392, 60.332] } },
            { "type": "Feature", "properties": { "Name": "Spittal Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.4275, 58.46] } },
            { "type": "Feature", "properties": { "Name": "Dersalloch", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.3969, 55.3242] } },
            { "type": "Feature", "properties": { "Name": "Shira", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.9783, 56.3547] } },
            { "type": "Feature", "properties": { "Name": "Broombank Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.7939, 57.5797] } },
            { "type": "Feature", "properties": { "Name": "Newfield Wind Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.3158, 55.1775] } },
            { "type": "Feature", "properties": { "Name": "Hare Hill Extension", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.1297, 55.3478] } },
            { "type": "Feature", "properties": { "Name": "Earlshaugh", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.4522, 55.4311] } },
            { "type": "Feature", "properties": { "Name": "Barnbackle", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.7683, 55.0386] } },
            { "type": "Feature", "properties": { "Name": "Ulzieside", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.9922, 55.3272] } },
            { "type": "Feature", "properties": { "Name": "Lieurary Hill Resubmission", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.5908, 58.5417] } },
            { "type": "Feature", "properties": { "Name": "Strathy North", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.0433, 58.4897] } },
            { "type": "Feature", "properties": { "Name": "Harelaw Renewable Energy Park", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.4289, 55.7364] } },
            { "type": "Feature", "properties": { "Name": "Doon Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.7969, 54.9753] } },
            { "type": "Feature", "properties": { "Name": "Dorenell - originally known as Scaut Hill Wind Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.1311, 57.3511] } },
            { "type": "Feature", "properties": { "Name": "Nigg Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.9808, 57.7089] } },
            { "type": "Feature", "properties": { "Name": "Kilchattan", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-5.5961, 55.3472] } },
            { "type": "Feature", "properties": { "Name": "Tom Nan Clach", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.8811, 57.3822] } },
            { "type": "Feature", "properties": { "Name": "Halsary", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.4061, 58.4333] } },
            { "type": "Feature", "properties": { "Name": "Mid Hill 2", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4606, 56.9644] } },
            { "type": "Feature", "properties": { "Name": "Andershaw", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.8739, 55.5225] } },
            { "type": "Feature", "properties": { "Name": "Tillymorgan", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.5786, 57.3997] } },
            { "type": "Feature", "properties": { "Name": "Blantyre Muir", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.1097, 55.7567] } },
            { "type": "Feature", "properties": { "Name": "Whitton", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3814, 55.4939] } },
            { "type": "Feature", "properties": { "Name": "Cowans Law", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.3444, 55.6478] } },
            { "type": "Feature", "properties": { "Name": "Rowantree", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.8611, 55.7375] } },
            { "type": "Feature", "properties": { "Name": "Muirpark", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.0317, 56.0636] } },
            { "type": "Feature", "properties": { "Name": "Strathy South", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.0661, 58.4297] } },
            { "type": "Feature", "properties": { "Name": "Wester Dod - Aikengall Extension", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4578, 55.9267] } },
            { "type": "Feature", "properties": { "Name": "Artfield Fell Ext", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.7664, 54.9661] } },
            { "type": "Feature", "properties": { "Name": "Hill of Ochiltree", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.613, 55.0445] } },
            { "type": "Feature", "properties": { "Name": "Minnygap resubmission", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.5317, 55.2514] } },
            { "type": "Feature", "properties": { "Name": "Calder Water Community windfarm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.2119, 55.6375] } },
            { "type": "Feature", "properties": { "Name": "Allt Duine", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.9856, 57.1986] } },
            { "type": "Feature", "properties": { "Name": "Breaker Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.8644, 55.1589] } },
            { "type": "Feature", "properties": { "Name": "Kinegar Quarry", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3806, 55.9206] } },
            { "type": "Feature", "properties": { "Name": "Standingfauld Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.8194, 56.2986] } },
            { "type": "Feature", "properties": { "Name": "Droop Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.38, 56.9155] } },
            { "type": "Feature", "properties": { "Name": "Beinn Greidaig Community Wind Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-6.4878, 58.2094] } },
            { "type": "Feature", "properties": { "Name": "Berriedale Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.9336, 58.8292] } },
            { "type": "Feature", "properties": { "Name": "Udny Community Wind Turbine", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.1842, 57.3172] } },
            { "type": "Feature", "properties": { "Name": "Auchenten", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-1.9333, 57.4072] } },
            { "type": "Feature", "properties": { "Name": "Ednie Farm II", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-1.8564, 57.5525] } },
            { "type": "Feature", "properties": { "Name": "Brockholes", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2986, 55.8617] } },
            { "type": "Feature", "properties": { "Name": "Spurlens Rig Wind Cluster", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.2003, 55.7717] } },
            { "type": "Feature", "properties": { "Name": "Gigha Community Wind farm Ext", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-5.7511, 55.6664] } },
            { "type": "Feature", "properties": { "Name": "Upper Wheedlemont Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.8767, 57.3189] } },
            { "type": "Feature", "properties": { "Name": "West Browncastle", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.11, 55.6] } },
            { "type": "Feature", "properties": { "Name": "Clatto Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.0628, 56.2555] } },
            { "type": "Feature", "properties": { "Name": "Moy Estate", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.0511, 57.3928] } },
            { "type": "Feature", "properties": { "Name": "Waterhead Moor resubmission", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.7872, 55.8242] } },
            { "type": "Feature", "properties": { "Name": "Muirake", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.7344, 57.61] } },
            { "type": "Feature", "properties": { "Name": "Earlseat", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.1039, 56.1742] } },
            { "type": "Feature", "properties": { "Name": "Dunbar", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4381, 55.975] } },
            { "type": "Feature", "properties": { "Name": "Wester Buthill Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.4481, 57.6683] } },
            { "type": "Feature", "properties": { "Name": "Fordoun Sawmill Wind Turbine", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4125, 56.8886] } },
            { "type": "Feature", "properties": { "Name": "Standingstone", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6786, 55.9542] } },
            { "type": "Feature", "properties": { "Name": "Corsbie Moor", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6347, 55.6994] } },
            { "type": "Feature", "properties": { "Name": "Burnside of Idoch", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3831, 57.5275] } },
            { "type": "Feature", "properties": { "Name": "Cairnhill Ext", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3792, 57.5672] } },
            { "type": "Feature", "properties": { "Name": "Girnal Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.863, 56.1455] } },
            { "type": "Feature", "properties": { "Name": "Shielburn Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.5347, 57.4939] } },
            { "type": "Feature", "properties": { "Name": "Latheronwheel", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.4253, 58.2886] } },
            { "type": "Feature", "properties": { "Name": "Cairnborrow", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.9089, 57.4655] } },
            { "type": "Feature", "properties": { "Name": "Land at Keith Inch and Green Hill", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-1.7678, 57.5194] } },
            { "type": "Feature", "properties": { "Name": "Bogenjohn Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.1, 57.5553] } },
            { "type": "Feature", "properties": { "Name": "Calcarb Factory", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.9983, 55.8322] } },
            { "type": "Feature", "properties": { "Name": "Assel Valley", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-4.8141, 55.2222] } },
            { "type": "Feature", "properties": { "Name": "Ethiebeaton Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.8469, 56.4992] } },
            { "type": "Feature", "properties": { "Name": "Carrach", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.1269, 56.6847] } },
            { "type": "Feature", "properties": { "Name": "North Mains Auchmaliddie", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.1947, 57.4967] } },
            { "type": "Feature", "properties": { "Name": "South Cassingray", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.8342, 56.2578] } },
            { "type": "Feature", "properties": { "Name": "Woodlands Farm (Turbine 2)", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2031, 57.3111] } },
            { "type": "Feature", "properties": { "Name": "Woodlands Farm (Turbine 1)", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2011, 57.31] } },
            { "type": "Feature", "properties": { "Name": "Hill of Fechel", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2383, 57.3172] } },
            { "type": "Feature", "properties": { "Name": "Mains of Auchreddie", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.1411, 57.398] } },
            { "type": "Feature", "properties": { "Name": "Cairnmore Ext", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.8217, 57.31] } },
            { "type": "Feature", "properties": { "Name": "Leyshade Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.9311, 56.5289] } },
            { "type": "Feature", "properties": { "Name": "Cartland Muir", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.7889, 55.7128] } },
            { "type": "Feature", "properties": { "Name": "North Balnoon", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6239, 57.4917] } },
            { "type": "Feature", "properties": { "Name": "Bridgend Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.5536, 55.9658] } },
            { "type": "Feature", "properties": { "Name": "Gowanfold", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-1.9653, 57.6572] } },
            { "type": "Feature", "properties": { "Name": "Loanhead of Fedderate", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2008, 57.5394] } },
            { "type": "Feature", "properties": { "Name": "Site at Hill of Easterton", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3867, 57.3742] } },
            { "type": "Feature", "properties": { "Name": "East Leylodge", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3706, 57.21] } },
            { "type": "Feature", "properties": { "Name": "Land at Shielbog", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.2803, 57.2903] } },
            { "type": "Feature", "properties": { "Name": "Land to North Eastof Brigton Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.5222, 56.8278] } },
            { "type": "Feature", "properties": { "Name": "Land at Duncanstown", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.7822, 57.4136] } },
            { "type": "Feature", "properties": { "Name": "Mossmoran", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.3231, 56.0917] } },
            { "type": "Feature", "properties": { "Name": "Blackburn Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3728, 55.8978] } },
            { "type": "Feature", "properties": { "Name": "Shiels Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4106, 56.8475] } },
            { "type": "Feature", "properties": { "Name": "Little Blairshinnoch", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6114, 57.6397] } },
            { "type": "Feature", "properties": { "Name": "Site at Hill of Culbirnie", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6178, 57.6311] } },
            { "type": "Feature", "properties": { "Name": "Site at Backhill Of Culbirnie", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.6172, 57.6361] } },
            { "type": "Feature", "properties": { "Name": "Spittal Farm", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-3.2761, 56.1322] } },
            { "type": "Feature", "properties": { "Name": "Lower Cushnie", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.3467, 57.6469] } },
            { "type": "Feature", "properties": { "Name": "Greenmoss", "Type": "proposed", "MW": null, "color": "orange" }, "geometry": { "type": "Point", "coordinates": [-2.4275, 57.2078] } }
        ]
    }
];